let stockProductos = [
    { id: 1, nombre: "Jordan 1 Mid Taxi1", tipo: "Zapatilla", precio: 98000, talle: 38, img: './Multimedia/jamarillas.jfif' },
    { id: 2, nombre: "Jordan 1 Mid Taxi2", tipo: "Zapatilla", precio: 98000, talle: 38, img: './Multimedia/jamarillas.jfif' },
    { id: 3, nombre: "Jordan 1 Mid Taxi3", tipo: "Zapatilla", precio: 98000, talle: 40, img: './Multimedia/jamarillas.jfif' },
    { id: 4, nombre: "Jordan 1 Mid Taxi4", tipo: "Zapatilla", precio: 98000, talle: 40, img: './Multimedia/jamarillas.jfif' },
    { id: 5, nombre: "Jordan 1 Mid Taxi5", tipo: "Zapatilla", precio: 98000, talle: 42, img: './Multimedia/jamarillas.jfif' },
    { id: 6, nombre: "Jordan 1 Mid Taxi6", tipo: "Zapatilla", precio: 98000, talle: 42, img: './Multimedia/jamarillas.jfif' },
    { id: 7, nombre: "Jordan 1 Mid Royal blue1", tipo: "Zapatilla", precio: 102000, talle: 38, img: './Multimedia/jazules.jfif' },
    { id: 8, nombre: "Jordan 1 Mid Royal blue2", tipo: "Zapatilla", precio: 102000, talle: 38, img: './Multimedia/jazules.jfif' },
    { id: 9, nombre: "Jordan 1 Mid Royal blue3", tipo: "Zapatilla", precio: 102000, talle: 40, img: './Multimedia/jazules.jfif'},
    { id: 10, nombre: "Jordan 1 Mid Royal blue4", tipo: "Zapatilla", precio: 102000, talle: 40, img: './Multimedia/jazules.jfif' },
    { id: 11, nombre: "Jordan 1 Mid Royal blue5", tipo: "Zapatilla", precio: 102000, talle: 40, img: './Multimedia/jazules.jfif' },
    { id: 12, nombre: "Jordan 1 Mid Royal blue6", tipo: "Zapatilla", precio: 102000, talle: 40, img: './Multimedia/jazules.jfif'},
    { id: 13, nombre: "Jordan 1 Mid University Blue1", tipo: "Zapatilla", precio: 125000, talle: 38, img: './Multimedia/jcelestes.jfif' },
    { id: 14, nombre: "Jordan 1 Mid University Blue2", tipo: "Zapatilla", precio: 125000, talle: 38, img: './Multimedia/jcelestes.jfif' },
    { id: 15, nombre: "Jordan 1 Mid University Blue3", tipo: "Zapatilla", precio: 125000, talle: 40, img: './Multimedia/jcelestes.jfif' },
    { id: 16, nombre: "Jordan 1 Mid University Blue4", tipo: "Zapatilla", precio: 125000, talle: 40, img: './Multimedia/jcelestes.jfif' },
    { id: 17, nombre: "Jordan 1 Mid University Blue5", tipo: "Zapatilla", precio: 125000, talle: 42, img: './Multimedia/jcelestes.jfif' },
    { id: 18, nombre: "Jordan 1 Mid University Blue6", tipo: "Zapatilla", precio: 125000, talle: 42, img: './Multimedia/jcelestes.jfif' },
    { id: 19, nombre: "Jordan 1 Mid Syracuse1", tipo: "Zapatilla", precio: 85000, talle: 38, img: './Multimedia/jnaranjas.jfif' },
    { id: 20, nombre: "Jordan 1 Mid Syracuse2", tipo: "Zapatilla", precio: 85000, talle: 38, img: './Multimedia/jnaranjas.jfif' },
    { id: 21, nombre: "Jordan 1 Mid Syracuse3", tipo: "Zapatilla", precio: 85000, talle: 40, img: './Multimedia/jnaranjas.jfif' },
    { id: 22, nombre: "Jordan 1 Mid Syracuse4", tipo: "Zapatilla", precio: 85000, talle: 40, img: './Multimedia/jnaranjas.jfif' },
    { id: 23, nombre: "Jordan 1 Mid Syracuse5", tipo: "Zapatilla", precio: 85000, talle: 42, img: './Multimedia/jnaranjas.jfif' },
    { id: 24, nombre: "Jordan 1 Mid Syracuse6", tipo: "Zapatilla", precio: 85000, talle: 42, img: './Multimedia/jnaranjas.jfif' },
]